version: '2.1'
services:
  neo4j:
    image: neo4j:5.22.0
    volumes:
      - ./data:/data
      - ./neo4j_plugins:/plugins
    ports: 
      - 7474:7474
      - 7687:7687
    environment:
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
      - NEO4JLABS_PLUGINS=["apoc"]
    